name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: self-hosted # This will run on your self-hosted runner
    steps:
      - name: Stop any existing pm2 processes (if any)
        run: |
          pm2 stop all || true

      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Specify the Node.js version you need

      - name: Copy .env file
        run: cp ../.env ./ # Copy the .env file from the parent directory

      - name: Install dependencies
        run: |
          npm install

      - name: Build the project
        run: |
          npm run build

      - name: Start the project with pm2
        run: |
          pm2 start npm --name "smartspend" -- run start
        env:
          NODE_ENV: production
